[build]
  command = "npm run build" # Replace with your build command
  publish = "dist" # Replace with your build output directory

[dev]
  framework = "solid" # Specify your framework if using Netlify Dev
